### ISSUE TITLE
ClassCastException with inferred spans

### ISSUE THREAD

**Issue by jackshirazi** [elastic/elastic-otel-java#236]
```
[otel.javaagent 2024-04-30 14:39:00:847 +0000] [elastic-inferred-spans] WARN co.elastic.otel.profiler.SamplingProfiler - Removing call tree for thread 38 because of exception while handling activation event: class java.lang.ClassCastException class io.opentelemetry.javaagent.shaded.io.opentelemetry.api.trace.PropagatedSpan cannot be cast to class io.opentelemetry.sdk.trace.ReadableSpan (io.opentelemetry.javaagent.shaded.io.opentelemetry.api.trace.PropagatedSpan is in unnamed module of loader 'bootstrap'; io.opentelemetry.sdk.trace.ReadableSpan is in unnamed module of loader io.opentelemetry.javaagent.bootstrap.AgentClassLoader @7ba4f24f)
```
using agent version 0.3.0

**Comment by JonasKunz** [comment]
I'm thinking that [this](https://github.com/elastic/elastic-otel-java/pull/218/files/4ef875ef2fabcd64535772400261814550981fa2#diff-121fb0a5bea62d54872ba237d3b936beae5dd330bc56f530b3e540bc9d5a3934R110) introduced the specific failure, because `LocalRootSpan` currently crashes when a `PropagatedSpan` is provided.

But even after we fix this, we need to look through our logic on span activation/deactivation.
In the previous elastic-apm-agent there were no `PropagatedSpans` and I didn't account for them when porting the feature.

**Comment by jackshirazi** [comment]
Still present in 0.3.1
```
[otel.javaagent 2024-05-03 12:53:13:817 +0000] [elastic-inferred-spans] WARN co.elastic.otel.profiler.SamplingProfiler - Removing call tree for thread 38 because of exception while handling activation event: class java.lang.ClassCastException class io.opentelemetry.javaagent.shaded.io.opentelemetry.api.trace.PropagatedSpan cannot be cast to class io.opentelemetry.sdk.trace.ReadableSpan (io.opentelemetry.javaagent.shaded.io.opentelemetry.api.trace.PropagatedSpan is in unnamed module of loader 'bootstrap'; io.opentelemetry.sdk.trace.ReadableSpan is in unnamed module of loader io.opentelemetry.javaagent.bootstrap.AgentClassLoader @7ba4f24f)
```

**Comment by JonasKunz** [comment]
Could you maybe run your scenario with debug logging enabled? This should print the stacktrace of the exception.

**Comment by jackshirazi** [comment]
Yes sorry

```
[otel.javaagent 2024-05-03 16:00:09:377 +0000] [elastic-inferred-spans] DEBUG co.elastic.otel.profiler.SamplingProfiler - class io.opentelemetry.javaagent.shaded.io.opentelemetry.api.trace.PropagatedSpan cannot be cast to class io.opentelemetry.sdk.trace.ReadableSpan (io.opentelemetry.javaagent.shaded.io.opentelemetry.api.trace.PropagatedSpan is in unnamed module of loader 'bootstrap'; io.opentelemetry.sdk.trace.ReadableSpan is in unnamed module of loader io.opentelemetry.javaagent.bootstrap.AgentClassLoader @7ba4f24f)
java.lang.ClassCastException: class io.opentelemetry.javaagent.shaded.io.opentelemetry.api.trace.PropagatedSpan cannot be cast to class io.opentelemetry.sdk.trace.ReadableSpan (io.opentelemetry.javaagent.shaded.io.opentelemetry.api.trace.PropagatedSpan is in unnamed module of loader 'bootstrap'; io.opentelemetry.sdk.trace.ReadableSpan is in unnamed module of loader io.opentelemetry.javaagent.bootstrap.AgentClassLoader @7ba4f24f)
        at co.elastic.otel.common.LocalRootSpan.getFor(LocalRootSpan.java:114)
        at co.elastic.otel.common.LocalRootSpan.onSpanStart(LocalRootSpan.java:78)
        at co.elastic.otel.UniversalProfilingProcessor.doOnStart(UniversalProfilingProcessor.java:177)
        at co.elastic.otel.common.AbstractChainingSpanProcessor.onStart(AbstractChainingSpanProcessor.java:74)
        at co.elastic.otel.common.AbstractChainingSpanProcessor.onStart(AbstractChainingSpanProcessor.java:78)
        at io.opentelemetry.sdk.trace.MultiSpanProcessor.onStart(MultiSpanProcessor.java:40)
        at io.opentelemetry.sdk.trace.SdkSpan.startSpan(SdkSpan.java:203)
        at io.opentelemetry.sdk.trace.SdkSpanBuilder.startSpan(SdkSpanBuilder.java:220)
        at co.elastic.otel.profiler.CallTree.asSpan(CallTree.java:520)
        at co.elastic.otel.profiler.CallTree.spanify(CallTree.java:452)
        at co.elastic.otel.profiler.CallTree.spanify(CallTree.java:460)
        at co.elastic.otel.profiler.CallTree.spanify(CallTree.java:460)
        at co.elastic.otel.profiler.CallTree.spanify(CallTree.java:460)
        at co.elastic.otel.profiler.CallTree.spanify(CallTree.java:460)
        at co.elastic.otel.profiler.CallTree$Root.spanify(CallTree.java:882)
        at co.elastic.otel.profiler.SamplingProfiler$ActivationEvent.stopProfiling(SamplingProfiler.java:971)
        at co.elastic.otel.profiler.SamplingProfiler$ActivationEvent.handleDeactivationEvent(SamplingProfiler.java:940)
        at co.elastic.otel.profiler.SamplingProfiler$ActivationEvent.handle(SamplingProfiler.java:888)
        at co.elastic.otel.profiler.SamplingProfiler.processActivationEventsUpTo(SamplingProfiler.java:641)
        at co.elastic.otel.profiler.SamplingProfiler.processTraces(SamplingProfiler.java:560)
        at co.elastic.otel.profiler.SamplingProfiler.profile(SamplingProfiler.java:423)
        at co.elastic.otel.profiler.SamplingProfiler.run(SamplingProfiler.java:376)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Thread.java:840)
```
